export const Countries = [
  { code: "AF", name: "Afghanistan", "dial-code": "+93" },
  { code: "AL", name: "Albania", "dial-code": "+355" },
  { code: "DZ", name: "Algeria", "dial-code": "+213" },
  { code: "AD", name: "Andorra", "dial-code": "+376" },
  { code: "AO", name: "Angola", "dial-code": "+244" },
  { code: "AG", name: "Antigua and Barbuda", "dial-code": "+1-268" },
  { code: "AR", name: "Argentina", "dial-code": "+54" },
  { code: "AW", name: "Armenia", "dial-code": "+297" },
  { code: "AU", name: "Australia", "dial-code": "+61" },
  { code: "AT", name: "Austria", "dial-code": "+43" },
  { code: "AZ", name: "Azerbaijan", "dial-code": "+994" },
  { code: "BS", name: "Bahamas", "dial-code": "+1-242" },
  { code: "BH", name: "Bahrain", "dial-code": "+973" },
  { code: "BD", name: "Bangladesh", "dial-code": "+880" },
  { code: "BB", name: "Barbados", "dial-code": "+1-246" },
  { code: "BY", name: "Belarus", "dial-code": "+375" },
  { code: "BE", name: "Belgium", "dial-code": "+32" },
  { code: "BZ", name: "Belize", "dial-code": "+501" },
  { code: "BJ", name: "Benin", "dial-code": "+229" },
  { code: "BT", name: "Bhutan", "dial-code": "+975" },
  { code: "BO", name: "Bolivia", "dial-code": "+591" },
  { code: "BA", name: "Bosnia and Herzegovina", "dial-code": "+387" },
  { code: "BW", name: "Botswana", "dial-code": "+267" },
  { code: "BR", name: "Brazil", "dial-code": "+55" },
  { code: "BN", name: "Brunei", "dial-code": "+673" },
  { code: "BG", name: "Bulgaria", "dial-code": "+359" },
  { code: "BF", name: "Burkina Faso", "dial-code": "+226" },
  { code: "BI", name: "Burundi", "dial-code": "+257" },
  { code: "KH", name: "Cambodia", "dial-code": "+855" },
  { code: "CM", name: "Cameroon", "dial-code": "+237" },
  { code: "CA", name: "Canada", "dial-code": "+1" },
  { code: "CV", name: "Cape Verde", "dial-code": "+238" },
  { code: "CF", name: "Central Africa Republic", "dial-code": "+236" },
  { code: "TD", name: "Chad", "dial-code": "+235" },
  { code: "CL", name: "Chile", "dial-code": "+56" },
  { code: "CN", name: "China", "dial-code": "+86" },
  { code: "CO", name: "Colombia", "dial-code": "+57" },
  { code: "KM", name: "Comoros", "dial-code": "+269" },
  { code: "CR", name: "Costa Rica", "dial-code": "+506" },
  { code: "HR", name: "Croatia", "dial-code": "+385" },
  { code: "CU", name: "Cuba", "dial-code": "+53" },
  { code: "CY", name: "Cyprus", "dial-code": "+357" },
  { code: "CZ", name: "Czech Republic", "dial-code": "+420" },
  { code: "CD", name: "Democratic Rep. of Congo", "dial-code": "+243" },
  { code: "Dk", name: "Denmark", "dial-code": "000" },
  { code: "DJ", name: "Djibouti", "dial-code": "+253" },
  { code: "DM", name: "Dominica", "dial-code": "+1-767" },
  { code: "DO", name: "Dominican Republic", "dial-code": "+1-809" },
  { code: "TL", name: "East Timor", "dial-code": "+670" },
  { code: "EC", name: "Ecuador", "dial-code": "+593" },
  { code: "EG", name: "Egypt", "dial-code": "+20" },
  { code: "SV", name: "El Salvador", "dial-code": "+503" },
  { code: "GQ", name: "Equatorial Guinea", "dial-code": "+240" },
  { code: "ER", name: "Eritrea", "dial-code": "+291" },
  { code: "EE", name: "Estonia", "dial-code": "+372" },
  { code: "ET", name: "Ethiopia", "dial-code": "+251" },
  { code: "FJ", name: "Fiji", "dial-code": "+679" },
  { code: "FI", name: "Finland", "dial-code": "+358" },
  { code: "FR", name: "France", "dial-code": "+33" },
  { code: "GA", name: "Gabon", "dial-code": "+241" },
  { code: "GM", name: "Gambia", "dial-code": "+220" },
  { code: "GE", name: "Georgia", "dial-code": "+995" },
  { code: "DE", name: "Germany", "dial-code": "+49" },
  { code: "GH", name: "Ghana", "dial-code": "+233" },
  { code: "GR", name: "Greece", "dial-code": "+30" },
  { code: "GD", name: "Grenada", "dial-code": "+1-473" },
  { code: "GT", name: "Guatemala", "dial-code": "+502" },
  { code: "GN", name: "Guinea ", "dial-code": "+224" },
  { code: "GW", name: "Guinea Bissau", "dial-code": "+245" },
  { code: "GY", name: "Guyana", "dial-code": "+592" },
  { code: "HT", name: "Haiti", "dial-code": "+509" },
  { code: "HN", name: "Honduras", "dial-code": "+504" },
  { code: "HU", name: "Hungary", "dial-code": "+36" },
  { code: "IS", name: "Iceland", "dial-code": "+354" },
  { code: "IN ", name: "India", "dial-code": "000" },
  { code: "ID", name: "Indonesia", "dial-code": "+62" },
  { code: "IR", name: "Iran", "dial-code": "+98" },
  { code: "IQ", name: "Iraq", "dial-code": "+964" },
  { code: "IE", name: "Ireland", "dial-code": "+353" },
  { code: "IL", name: "Israel", "dial-code": "+972" },
  { code: "IT", name: "Italy", "dial-code": "+39" },
  { code: "CI", name: "Ivory Coast", "dial-code": "+225" },
  { code: "JM", name: "Jamaica", "dial-code": "+1-876" },
  { code: "JP", name: "Japan", "dial-code": "+81" },
  { code: "JO", name: "Jordan", "dial-code": "+962" },
  { code: "KZ", name: "Kazakhstan", "dial-code": "+7" },
  { code: "KE", name: "Kenya", "dial-code": "+254" },
  { code: "KI", name: "Kiribati", "dial-code": "+686" },
  { code: "XK", name: "Kosovo", "dial-code": "+383" },
  { code: "KW", name: "Kuwait", "dial-code": "+965" },
  { code: "KG", name: "Kyrgyzstan", "dial-code": "+996" },
  { code: "LA", name: "Laos", "dial-code": "+856" },
  { code: "LV", name: "Latvia", "dial-code": "+371" },
  { code: "LB", name: "Lebanon", "dial-code": "+961" },
  { code: "LS", name: "Lesotho", "dial-code": "+266" },
  { code: "LR", name: "Liberia", "dial-code": "+231" },
  { code: "LY", name: "Libya", "dial-code": "+218" },
  { code: "LI", name: "Liechtenstein", "dial-code": "+423" },
  { code: "LT", name: "Lithuania", "dial-code": "+370" },
  { code: "LU", name: "Luxembourg", "dial-code": "+352" },
  { code: "MK", name: "Macedonia (FYROM)", "dial-code": "+389" },
  { code: "MG", name: "Madagascar", "dial-code": "+261" },
  { code: "MW", name: "Malawi", "dial-code": "+265" },
  { code: "MY", name: "Malaysia", "dial-code": "+60" },
  { code: "MV", name: "Maldives", "dial-code": "+960" },
  { code: "ML", name: "Mali", "dial-code": "+223" },
  { code: "MT", name: "Malta", "dial-code": "+356" },
  { code: "MH", name: "Marshall Islands", "dial-code": "+692" },
  { code: "MR", name: "Mauritania", "dial-code": "+222" },
  { code: "MU", name: "Mauritius", "dial-code": "+230" },
  { code: "MX", name: "Mexico", "dial-code": "+52" },
  { code: "FM", name: "Micronesia", "dial-code": "+691" },
  { code: "MD", name: "Moldova", "dial-code": "+373" },
  { code: "MC", name: "Monaco", "dial-code": "+377" },
  { code: "MN", name: "Mongolia", "dial-code": "+976" },
  { code: "ME", name: "Montenegro", "dial-code": "+382" },
  { code: "MA", name: "Morocco", "dial-code": "+212" },
  { code: "MZ", name: "Mozambique", "dial-code": "+258" },
  { code: "MM", name: "Myanmar (Burma)", "dial-code": "+95" },
  { code: "NA", name: "Nambia", "dial-code": "+264" },
  { code: "NR", name: "Nauru", "dial-code": "+674" },
  { code: "NP", name: "Nepal", "dial-code": "+977" },
  { code: "NL", name: "Netherlands", "dial-code": "+31" },
  { code: "NZ", name: "New Zealand", "dial-code": "+64" },
  { code: "NI", name: "Nicaragua", "dial-code": "+505" },
  { code: "NE", name: "Niger", "dial-code": "+227" },
  { code: "NG", name: "Nigeria", "dial-code": "+234" },
  { code: "KP", name: "North Korea", "dial-code": "+850" },
  { code: "NO", name: "Norway", "dial-code": "+47" },
  { code: "OM", name: "Oman", "dial-code": "+968" },
  { code: "PK", name: "Pakistan", "dial-code": "+92" },
  { code: "PW", name: "Palau", "dial-code": "+680" },
  { code: "PS", name: "Palestine", "dial-code": "+970" },
  { code: "PA", name: "Panama", "dial-code": "+507" },
  { code: "PG", name: "Papua New Guinea", "dial-code": "+675" },
  { code: "PY", name: "Paraguay", "dial-code": "+595" },
  { code: "PE", name: "Peru", "dial-code": "+51" },
  { code: "PH", name: "Philippines", "dial-code": "+63" },
  { code: "PL", name: "Poland", "dial-code": "+48" },
  { code: "PT", name: "Portugal", "dial-code": "+351" },
  { code: "QA", name: "Qatar", "dial-code": "+974" },
  { code: "CG", name: "Rep. of Congo", "dial-code": "+242" },
  { code: "SS", name: "Rep. of South Sundan", "dial-code": "+211" },
  { code: "RO", name: "Romania", "dial-code": "+40" },
  { code: "RU", name: "Russia", "dial-code": "+7" },
  { code: "RW", name: "Rwanda", "dial-code": "+250" },
  { code: "KN", name: "Saint Kitts and Nevis", "dial-code": "+1-869" },
  { code: "LC", name: "Saint Lucia", "dial-code": "+1-758" },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    "dial-code": "+1-784",
  },
  { code: "WS", name: "Samoa", "dial-code": "+685" },
  { code: "SM", name: "San Marino", "dial-code": "+378" },
  { code: "SA", name: "Saudi Arabia", "dial-code": "+966" },
  { code: "SN", name: "Senegal", "dial-code": "+221" },
  { code: "RS", name: "Serbia", "dial-code": "+381" },
  { code: "SC", name: "Seychelles", "dial-code": "+248" },
  { code: "SL", name: "Sierra Leone", "dial-code": "+232" },
  { code: "SG", name: "Singapore", "dial-code": "+65" },
  { code: "SK", name: "Slovakia", "dial-code": "+421" },
  { code: "SI", name: "Slovenia", "dial-code": "+386" },
  { code: "ST", name: "Soa Tome & Principle", "dial-code": "+239" },
  { code: "SB", name: "Solomon Islands", "dial-code": "+677" },
  { code: "SO", name: "Somalia", "dial-code": "+252" },
  { code: "ZA", name: "South Africa", "dial-code": "+27" },
  { code: "KR", name: "South Korea", "dial-code": "+82" },
  { code: "ES", name: "Spain", "dial-code": "+34" },
  { code: "LK", name: "Sri Lanka", "dial-code": "+94" },
  { code: "SD", name: "Sudan (North)", "dial-code": "+249" },
  { code: "SR", name: "Suriname", "dial-code": "+597" },
  { code: "SZ", name: "Swaziland", "dial-code": "+268" },
  { code: "SE", name: "Sweden", "dial-code": "+46" },
  { code: "CH", name: "Switzerland", "dial-code": "+41" },
  { code: "SY", name: "Syria", "dial-code": "+963" },
  { code: "TW", name: "Taiwan", "dial-code": "+886" },
  { code: "TJ", name: "Tajikistan", "dial-code": "+992" },
  { code: "TZ", name: "Tanzania", "dial-code": "+255" },
  { code: "TH", name: "Thailand", "dial-code": "+66" },
  { code: "TG", name: "Togo", "dial-code": "+228" },
  { code: "TO", name: "Tonga", "dial-code": "+676" },
  { code: "TT", name: "Trinidad and Tobago", "dial-code": "+1-868" },
  { code: "TN", name: "Tunisia", "dial-code": "+216" },
  { code: "TR", name: "Turkey", "dial-code": "+90" },
  { code: "TM", name: "Turkmenistan", "dial-code": "+993" },
  { code: "TV", name: "Tuvalu", "dial-code": "+688" },
  { code: "UG", name: "Uganda", "dial-code": "+256" },
  { code: "UA", name: "Ukraine", "dial-code": "+380" },
  { code: "AE", name: "United Arab Emirates", "dial-code": "+971" },
  { code: "GB", name: "United Kingdom", "dial-code": "+44" },
  { code: "US", name: "United States of America", "dial-code": "+1" },
  { code: "UY", name: "Uruguay", "dial-code": "+598" },
  { code: "UZ", name: "Uzbekistan", "dial-code": "+998" },
  { code: "VU", name: "Vanuatu", "dial-code": "+678" },
  { code: "VA", name: "Vatican City ", "dial-code": "+379" },
  { code: "VE", name: "Venezuela", "dial-code": "+58" },
  { code: "VN", name: "Vietnam", "dial-code": "+84" },
  { code: "YE", name: "Yemen", "dial-code": "+967" },
  { code: "ZM", name: "Zambia", "dial-code": "+260" },
  { code: "ZW", name: "Zimbabwe", "dial-code": "+263" },
]
export const timezones = [
  {
    value: "Dateline Standard Time",
    abbr: "DST",
    offset: -12,
    isdst: false,
    text: "(UTC-12:00) International Date Line West",
    utc: ["Etc/GMT+12"],
  },
  {
    value: "UTC-11",
    abbr: "U",
    offset: -11,
    isdst: false,
    text: "(UTC-11:00) Coordinated Universal Time-11",
    utc: ["Etc/GMT+11", "Pacific/Midway", "Pacific/Niue", "Pacific/Pago_Pago"],
  },
  {
    value: "Hawaiian Standard Time",
    abbr: "HST",
    offset: -10,
    isdst: false,
    text: "(UTC-10:00) Hawaii",
    utc: [
      "Etc/GMT+10",
      "Pacific/Honolulu",
      "Pacific/Johnston",
      "Pacific/Rarotonga",
      "Pacific/Tahiti",
    ],
  },
  {
    value: "Alaskan Standard Time",
    abbr: "AKDT",
    offset: -8,
    isdst: true,
    text: "(UTC-09:00) Alaska",
    utc: [
      "America/Anchorage",
      "America/Juneau",
      "America/Nome",
      "America/Sitka",
      "America/Yakutat",
    ],
  },
  {
    value: "Pacific Standard Time (Mexico)",
    abbr: "PDT",
    offset: -7,
    isdst: true,
    text: "(UTC-08:00) Baja California",
    utc: ["America/Santa_Isabel"],
  },
  {
    value: "Pacific Daylight Time",
    abbr: "PDT",
    offset: -7,
    isdst: true,
    text: "(UTC-07:00) Pacific Daylight Time (US & Canada)",
    utc: ["America/Los_Angeles", "America/Tijuana", "America/Vancouver"],
  },
  {
    value: "Pacific Standard Time",
    abbr: "PST",
    offset: -8,
    isdst: false,
    text: "(UTC-08:00) Pacific Standard Time (US & Canada)",
    utc: [
      "America/Los_Angeles",
      "America/Tijuana",
      "America/Vancouver",
      "PST8PDT",
    ],
  },
  {
    value: "US Mountain Standard Time",
    abbr: "UMST",
    offset: -7,
    isdst: false,
    text: "(UTC-07:00) Arizona",
    utc: [
      "America/Creston",
      "America/Dawson",
      "America/Dawson_Creek",
      "America/Hermosillo",
      "America/Phoenix",
      "America/Whitehorse",
      "Etc/GMT+7",
    ],
  },
  {
    value: "Mountain Standard Time (Mexico)",
    abbr: "MDT",
    offset: -6,
    isdst: true,
    text: "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
    utc: ["America/Chihuahua", "America/Mazatlan"],
  },
  {
    value: "Mountain Standard Time",
    abbr: "MDT",
    offset: -6,
    isdst: true,
    text: "(UTC-07:00) Mountain Time (US & Canada)",
    utc: [
      "America/Boise",
      "America/Cambridge_Bay",
      "America/Denver",
      "America/Edmonton",
      "America/Inuvik",
      "America/Ojinaga",
      "America/Yellowknife",
      "MST7MDT",
    ],
  },
  {
    value: "Central America Standard Time",
    abbr: "CAST",
    offset: -6,
    isdst: false,
    text: "(UTC-06:00) Central America",
    utc: [
      "America/Belize",
      "America/Costa_Rica",
      "America/El_Salvador",
      "America/Guatemala",
      "America/Managua",
      "America/Tegucigalpa",
      "Etc/GMT+6",
      "Pacific/Galapagos",
    ],
  },
  {
    value: "Central Standard Time",
    abbr: "CDT",
    offset: -5,
    isdst: true,
    text: "(UTC-06:00) Central Time (US & Canada)",
    utc: [
      "America/Chicago",
      "America/Indiana/Knox",
      "America/Indiana/Tell_City",
      "America/Matamoros",
      "America/Menominee",
      "America/North_Dakota/Beulah",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "America/Rainy_River",
      "America/Rankin_Inlet",
      "America/Resolute",
      "America/Winnipeg",
      "CST6CDT",
    ],
  },
  {
    value: "Central Standard Time (Mexico)",
    abbr: "CDT",
    offset: -5,
    isdst: true,
    text: "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
    utc: [
      "America/Bahia_Banderas",
      "America/Cancun",
      "America/Merida",
      "America/Mexico_City",
      "America/Monterrey",
    ],
  },
  {
    value: "Canada Central Standard Time",
    abbr: "CCST",
    offset: -6,
    isdst: false,
    text: "(UTC-06:00) Saskatchewan",
    utc: ["America/Regina", "America/Swift_Current"],
  },
  {
    value: "SA Pacific Standard Time",
    abbr: "SPST",
    offset: -5,
    isdst: false,
    text: "(UTC-05:00) Bogota, Lima, Quito",
    utc: [
      "America/Bogota",
      "America/Cayman",
      "America/Coral_Harbour",
      "America/Eirunepe",
      "America/Guayaquil",
      "America/Jamaica",
      "America/Lima",
      "America/Panama",
      "America/Rio_Branco",
      "Etc/GMT+5",
    ],
  },
  {
    value: "Eastern Standard Time",
    abbr: "EST",
    offset: -5,
    isdst: false,
    text: "(UTC-05:00) Eastern Time (US & Canada)",
    utc: [
      "America/Detroit",
      "America/Havana",
      "America/Indiana/Petersburg",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Iqaluit",
      "America/Kentucky/Monticello",
      "America/Louisville",
      "America/Montreal",
      "America/Nassau",
      "America/New_York",
      "America/Nipigon",
      "America/Pangnirtung",
      "America/Port-au-Prince",
      "America/Thunder_Bay",
      "America/Toronto",
    ],
  },
  {
    value: "Eastern Daylight Time",
    abbr: "EDT",
    offset: -4,
    isdst: true,
    text: "(UTC-04:00) Eastern Daylight Time (US & Canada)",
    utc: [
      "America/Detroit",
      "America/Havana",
      "America/Indiana/Petersburg",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Iqaluit",
      "America/Kentucky/Monticello",
      "America/Louisville",
      "America/Montreal",
      "America/Nassau",
      "America/New_York",
      "America/Nipigon",
      "America/Pangnirtung",
      "America/Port-au-Prince",
      "America/Thunder_Bay",
      "America/Toronto",
    ],
  },
  {
    value: "US Eastern Standard Time",
    abbr: "UEDT",
    offset: -5,
    isdst: false,
    text: "(UTC-05:00) Indiana (East)",
    utc: [
      "America/Indiana/Marengo",
      "America/Indiana/Vevay",
      "America/Indianapolis",
    ],
  },
  {
    value: "Venezuela Standard Time",
    abbr: "VST",
    offset: -4.5,
    isdst: false,
    text: "(UTC-04:30) Caracas",
    utc: ["America/Caracas"],
  },
  {
    value: "Paraguay Standard Time",
    abbr: "PYT",
    offset: -4,
    isdst: false,
    text: "(UTC-04:00) Asuncion",
    utc: ["America/Asuncion"],
  },
  {
    value: "Atlantic Standard Time",
    abbr: "ADT",
    offset: -3,
    isdst: true,
    text: "(UTC-04:00) Atlantic Time (Canada)",
    utc: [
      "America/Glace_Bay",
      "America/Goose_Bay",
      "America/Halifax",
      "America/Moncton",
      "America/Thule",
      "Atlantic/Bermuda",
    ],
  },
  {
    value: "Central Brazilian Standard Time",
    abbr: "CBST",
    offset: -4,
    isdst: false,
    text: "(UTC-04:00) Cuiaba",
    utc: ["America/Campo_Grande", "America/Cuiaba"],
  },
  {
    value: "SA Western Standard Time",
    abbr: "SWST",
    offset: -4,
    isdst: false,
    text: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
    utc: [
      "America/Anguilla",
      "America/Antigua",
      "America/Aruba",
      "America/Barbados",
      "America/Blanc-Sablon",
      "America/Boa_Vista",
      "America/Curacao",
      "America/Dominica",
      "America/Grand_Turk",
      "America/Grenada",
      "America/Guadeloupe",
      "America/Guyana",
      "America/Kralendijk",
      "America/La_Paz",
      "America/Lower_Princes",
      "America/Manaus",
      "America/Marigot",
      "America/Martinique",
      "America/Montserrat",
      "America/Port_of_Spain",
      "America/Porto_Velho",
      "America/Puerto_Rico",
      "America/Santo_Domingo",
      "America/St_Barthelemy",
      "America/St_Kitts",
      "America/St_Lucia",
      "America/St_Thomas",
      "America/St_Vincent",
      "America/Tortola",
      "Etc/GMT+4",
    ],
  },
  {
    value: "Pacific SA Standard Time",
    abbr: "PSST",
    offset: -4,
    isdst: false,
    text: "(UTC-04:00) Santiago",
    utc: ["America/Santiago", "Antarctica/Palmer"],
  },
  {
    value: "Newfoundland Standard Time",
    abbr: "NDT",
    offset: -2.5,
    isdst: true,
    text: "(UTC-03:30) Newfoundland",
    utc: ["America/St_Johns"],
  },
  {
    value: "E. South America Standard Time",
    abbr: "ESAST",
    offset: -3,
    isdst: false,
    text: "(UTC-03:00) Brasilia",
    utc: ["America/Sao_Paulo"],
  },
  {
    value: "Argentina Standard Time",
    abbr: "AST",
    offset: -3,
    isdst: false,
    text: "(UTC-03:00) Buenos Aires",
    utc: [
      "America/Argentina/Buenos_Aires",
      "America/Argentina/Catamarca",
      "America/Argentina/Cordoba",
      "America/Argentina/Jujuy",
      "America/Argentina/La_Rioja",
      "America/Argentina/Mendoza",
      "America/Argentina/Rio_Gallegos",
      "America/Argentina/Salta",
      "America/Argentina/San_Juan",
      "America/Argentina/San_Luis",
      "America/Argentina/Tucuman",
      "America/Argentina/Ushuaia",
      "America/Buenos_Aires",
      "America/Catamarca",
      "America/Cordoba",
      "America/Jujuy",
      "America/Mendoza",
    ],
  },
  {
    value: "SA Eastern Standard Time",
    abbr: "SEST",
    offset: -3,
    isdst: false,
    text: "(UTC-03:00) Cayenne, Fortaleza",
    utc: [
      "America/Araguaina",
      "America/Belem",
      "America/Cayenne",
      "America/Fortaleza",
      "America/Maceio",
      "America/Paramaribo",
      "America/Recife",
      "America/Santarem",
      "Antarctica/Rothera",
      "Atlantic/Stanley",
      "Etc/GMT+3",
    ],
  },
  {
    value: "Greenland Standard Time",
    abbr: "GDT",
    offset: -3,
    isdst: true,
    text: "(UTC-03:00) Greenland",
    utc: ["America/Godthab"],
  },
  {
    value: "Montevideo Standard Time",
    abbr: "MST",
    offset: -3,
    isdst: false,
    text: "(UTC-03:00) Montevideo",
    utc: ["America/Montevideo"],
  },
  {
    value: "Bahia Standard Time",
    abbr: "BST",
    offset: -3,
    isdst: false,
    text: "(UTC-03:00) Salvador",
    utc: ["America/Bahia"],
  },
  {
    value: "UTC-02",
    abbr: "U",
    offset: -2,
    isdst: false,
    text: "(UTC-02:00) Coordinated Universal Time-02",
    utc: ["America/Noronha", "Atlantic/South_Georgia", "Etc/GMT+2"],
  },
  {
    value: "Mid-Atlantic Standard Time",
    abbr: "MDT",
    offset: -1,
    isdst: true,
    text: "(UTC-02:00) Mid-Atlantic - Old",
    utc: [],
  },
  {
    value: "Azores Standard Time",
    abbr: "ADT",
    offset: 0,
    isdst: true,
    text: "(UTC-01:00) Azores",
    utc: ["America/Scoresbysund", "Atlantic/Azores"],
  },
  {
    value: "Cape Verde Standard Time",
    abbr: "CVST",
    offset: -1,
    isdst: false,
    text: "(UTC-01:00) Cape Verde Is.",
    utc: ["Atlantic/Cape_Verde", "Etc/GMT+1"],
  },
  {
    value: "Morocco Standard Time",
    abbr: "MDT",
    offset: 1,
    isdst: true,
    text: "(UTC) Casablanca",
    utc: ["Africa/Casablanca", "Africa/El_Aaiun"],
  },
  {
    value: "UTC",
    abbr: "UTC",
    offset: 0,
    isdst: false,
    text: "(UTC) Coordinated Universal Time",
    utc: ["America/Danmarkshavn", "Etc/GMT"],
  },
  {
    value: "GMT Standard Time",
    abbr: "GMT",
    offset: 0,
    isdst: false,
    text: "(UTC) Edinburgh, London",
    utc: [
      "Europe/Isle_of_Man",
      "Europe/Guernsey",
      "Europe/Jersey",
      "Europe/London",
    ],
  },
  {
    value: "British Summer Time",
    abbr: "BST",
    offset: 1,
    isdst: true,
    text: "(UTC+01:00) Edinburgh, London",
    utc: [
      "Europe/Isle_of_Man",
      "Europe/Guernsey",
      "Europe/Jersey",
      "Europe/London",
    ],
  },
  {
    value: "GMT Standard Time",
    abbr: "GDT",
    offset: 1,
    isdst: true,
    text: "(UTC) Dublin, Lisbon",
    utc: [
      "Atlantic/Canary",
      "Atlantic/Faeroe",
      "Atlantic/Madeira",
      "Europe/Dublin",
      "Europe/Lisbon",
    ],
  },
  {
    value: "Greenwich Standard Time",
    abbr: "GST",
    offset: 0,
    isdst: false,
    text: "(UTC) Monrovia, Reykjavik",
    utc: [
      "Africa/Abidjan",
      "Africa/Accra",
      "Africa/Bamako",
      "Africa/Banjul",
      "Africa/Bissau",
      "Africa/Conakry",
      "Africa/Dakar",
      "Africa/Freetown",
      "Africa/Lome",
      "Africa/Monrovia",
      "Africa/Nouakchott",
      "Africa/Ouagadougou",
      "Africa/Sao_Tome",
      "Atlantic/Reykjavik",
      "Atlantic/St_Helena",
    ],
  },
  {
    value: "W. Europe Standard Time",
    abbr: "WEDT",
    offset: 2,
    isdst: true,
    text: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    utc: [
      "Arctic/Longyearbyen",
      "Europe/Amsterdam",
      "Europe/Andorra",
      "Europe/Berlin",
      "Europe/Busingen",
      "Europe/Gibraltar",
      "Europe/Luxembourg",
      "Europe/Malta",
      "Europe/Monaco",
      "Europe/Oslo",
      "Europe/Rome",
      "Europe/San_Marino",
      "Europe/Stockholm",
      "Europe/Vaduz",
      "Europe/Vatican",
      "Europe/Vienna",
      "Europe/Zurich",
    ],
  },
  {
    value: "Central Europe Standard Time",
    abbr: "CEDT",
    offset: 2,
    isdst: true,
    text: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    utc: [
      "Europe/Belgrade",
      "Europe/Bratislava",
      "Europe/Budapest",
      "Europe/Ljubljana",
      "Europe/Podgorica",
      "Europe/Prague",
      "Europe/Tirane",
    ],
  },
  {
    value: "Romance Standard Time",
    abbr: "RDT",
    offset: 2,
    isdst: true,
    text: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
    utc: [
      "Africa/Ceuta",
      "Europe/Brussels",
      "Europe/Copenhagen",
      "Europe/Madrid",
      "Europe/Paris",
    ],
  },
  {
    value: "Central European Standard Time",
    abbr: "CEDT",
    offset: 2,
    isdst: true,
    text: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
    utc: ["Europe/Sarajevo", "Europe/Skopje", "Europe/Warsaw", "Europe/Zagreb"],
  },
  {
    value: "W. Central Africa Standard Time",
    abbr: "WCAST",
    offset: 1,
    isdst: false,
    text: "(UTC+01:00) West Central Africa",
    utc: [
      "Africa/Algiers",
      "Africa/Bangui",
      "Africa/Brazzaville",
      "Africa/Douala",
      "Africa/Kinshasa",
      "Africa/Lagos",
      "Africa/Libreville",
      "Africa/Luanda",
      "Africa/Malabo",
      "Africa/Ndjamena",
      "Africa/Niamey",
      "Africa/Porto-Novo",
      "Africa/Tunis",
      "Etc/GMT-1",
    ],
  },
  {
    value: "Namibia Standard Time",
    abbr: "NST",
    offset: 1,
    isdst: false,
    text: "(UTC+01:00) Windhoek",
    utc: ["Africa/Windhoek"],
  },
  {
    value: "GTB Standard Time",
    abbr: "GDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) Athens, Bucharest",
    utc: [
      "Asia/Nicosia",
      "Europe/Athens",
      "Europe/Bucharest",
      "Europe/Chisinau",
    ],
  },
  {
    value: "Middle East Standard Time",
    abbr: "MEDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) Beirut",
    utc: ["Asia/Beirut"],
  },
  {
    value: "Egypt Standard Time",
    abbr: "EST",
    offset: 2,
    isdst: false,
    text: "(UTC+02:00) Cairo",
    utc: ["Africa/Cairo"],
  },
  {
    value: "Syria Standard Time",
    abbr: "SDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) Damascus",
    utc: ["Asia/Damascus"],
  },
  {
    value: "E. Europe Standard Time",
    abbr: "EEDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) E. Europe",
    utc: [
      "Asia/Nicosia",
      "Europe/Athens",
      "Europe/Bucharest",
      "Europe/Chisinau",
      "Europe/Helsinki",
      "Europe/Kiev",
      "Europe/Mariehamn",
      "Europe/Nicosia",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Uzhgorod",
      "Europe/Vilnius",
      "Europe/Zaporozhye",
    ],
  },
  {
    value: "South Africa Standard Time",
    abbr: "SAST",
    offset: 2,
    isdst: false,
    text: "(UTC+02:00) Harare, Pretoria",
    utc: [
      "Africa/Blantyre",
      "Africa/Bujumbura",
      "Africa/Gaborone",
      "Africa/Harare",
      "Africa/Johannesburg",
      "Africa/Kigali",
      "Africa/Lubumbashi",
      "Africa/Lusaka",
      "Africa/Maputo",
      "Africa/Maseru",
      "Africa/Mbabane",
      "Etc/GMT-2",
    ],
  },
  {
    value: "FLE Standard Time",
    abbr: "FDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    utc: [
      "Europe/Helsinki",
      "Europe/Kiev",
      "Europe/Mariehamn",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Uzhgorod",
      "Europe/Vilnius",
      "Europe/Zaporozhye",
    ],
  },
  {
    value: "Turkey Standard Time",
    abbr: "TDT",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Istanbul",
    utc: ["Europe/Istanbul"],
  },
  {
    value: "Israel Standard Time",
    abbr: "JDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) Jerusalem",
    utc: ["Asia/Jerusalem"],
  },
  {
    value: "Libya Standard Time",
    abbr: "LST",
    offset: 2,
    isdst: false,
    text: "(UTC+02:00) Tripoli",
    utc: ["Africa/Tripoli"],
  },
  {
    value: "Jordan Standard Time",
    abbr: "JST",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Amman",
    utc: ["Asia/Amman"],
  },
  {
    value: "Arabic Standard Time",
    abbr: "AST",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Baghdad",
    utc: ["Asia/Baghdad"],
  },
  {
    value: "Kaliningrad Standard Time",
    abbr: "KST",
    offset: 3,
    isdst: false,
    text: "(UTC+02:00) Kaliningrad",
    utc: ["Europe/Kaliningrad"],
  },
  {
    value: "Arab Standard Time",
    abbr: "AST",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Kuwait, Riyadh",
    utc: [
      "Asia/Aden",
      "Asia/Bahrain",
      "Asia/Kuwait",
      "Asia/Qatar",
      "Asia/Riyadh",
    ],
  },
  {
    value: "E. Africa Standard Time",
    abbr: "EAST",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Nairobi",
    utc: [
      "Africa/Addis_Ababa",
      "Africa/Asmera",
      "Africa/Dar_es_Salaam",
      "Africa/Djibouti",
      "Africa/Juba",
      "Africa/Kampala",
      "Africa/Khartoum",
      "Africa/Mogadishu",
      "Africa/Nairobi",
      "Antarctica/Syowa",
      "Etc/GMT-3",
      "Indian/Antananarivo",
      "Indian/Comoro",
      "Indian/Mayotte",
    ],
  },
  {
    value: "Moscow Standard Time",
    abbr: "MSK",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk",
    utc: [
      "Europe/Kirov",
      "Europe/Moscow",
      "Europe/Simferopol",
      "Europe/Volgograd",
      "Europe/Minsk",
    ],
  },
  {
    value: "Samara Time",
    abbr: "SAMT",
    offset: 4,
    isdst: false,
    text: "(UTC+04:00) Samara, Ulyanovsk, Saratov",
    utc: ["Europe/Astrakhan", "Europe/Samara", "Europe/Ulyanovsk"],
  },
  {
    value: "Iran Standard Time",
    abbr: "IDT",
    offset: 4.5,
    isdst: true,
    text: "(UTC+03:30) Tehran",
    utc: ["Asia/Tehran"],
  },
  {
    value: "Arabian Standard Time",
    abbr: "AST",
    offset: 4,
    isdst: false,
    text: "(UTC+04:00) Abu Dhabi, Muscat",
    utc: ["Asia/Dubai", "Asia/Muscat", "Etc/GMT-4"],
  },
  {
    value: "Azerbaijan Standard Time",
    abbr: "ADT",
    offset: 5,
    isdst: true,
    text: "(UTC+04:00) Baku",
    utc: ["Asia/Baku"],
  },
  {
    value: "Mauritius Standard Time",
    abbr: "MST",
    offset: 4,
    isdst: false,
    text: "(UTC+04:00) Port Louis",
    utc: ["Indian/Mahe", "Indian/Mauritius", "Indian/Reunion"],
  },
  {
    value: "Georgian Standard Time",
    abbr: "GET",
    offset: 4,
    isdst: false,
    text: "(UTC+04:00) Tbilisi",
    utc: ["Asia/Tbilisi"],
  },
  {
    value: "Caucasus Standard Time",
    abbr: "CST",
    offset: 4,
    isdst: false,
    text: "(UTC+04:00) Yerevan",
    utc: ["Asia/Yerevan"],
  },
  {
    value: "Afghanistan Standard Time",
    abbr: "AST",
    offset: 4.5,
    isdst: false,
    text: "(UTC+04:30) Kabul",
    utc: ["Asia/Kabul"],
  },
  {
    value: "West Asia Standard Time",
    abbr: "WAST",
    offset: 5,
    isdst: false,
    text: "(UTC+05:00) Ashgabat, Tashkent",
    utc: [
      "Antarctica/Mawson",
      "Asia/Aqtau",
      "Asia/Aqtobe",
      "Asia/Ashgabat",
      "Asia/Dushanbe",
      "Asia/Oral",
      "Asia/Samarkand",
      "Asia/Tashkent",
      "Etc/GMT-5",
      "Indian/Kerguelen",
      "Indian/Maldives",
    ],
  },
  {
    value: "Yekaterinburg Time",
    abbr: "YEKT",
    offset: 5,
    isdst: false,
    text: "(UTC+05:00) Yekaterinburg",
    utc: ["Asia/Yekaterinburg"],
  },
  {
    value: "Pakistan Standard Time",
    abbr: "PKT",
    offset: 5,
    isdst: false,
    text: "(UTC+05:00) Islamabad, Karachi",
    utc: ["Asia/Karachi"],
  },
  {
    value: "India Standard Time",
    abbr: "IST",
    offset: 5.5,
    isdst: false,
    text: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
    utc: ["Asia/Kolkata", "Asia/Calcutta"],
  },
  {
    value: "Sri Lanka Standard Time",
    abbr: "SLST",
    offset: 5.5,
    isdst: false,
    text: "(UTC+05:30) Sri Jayawardenepura",
    utc: ["Asia/Colombo"],
  },
  {
    value: "Nepal Standard Time",
    abbr: "NST",
    offset: 5.75,
    isdst: false,
    text: "(UTC+05:45) Kathmandu",
    utc: ["Asia/Kathmandu"],
  },
  {
    value: "Central Asia Standard Time",
    abbr: "CAST",
    offset: 6,
    isdst: false,
    text: "(UTC+06:00) Nur-Sultan (Astana)",
    utc: [
      "Antarctica/Vostok",
      "Asia/Almaty",
      "Asia/Bishkek",
      "Asia/Qyzylorda",
      "Asia/Urumqi",
      "Etc/GMT-6",
      "Indian/Chagos",
    ],
  },
  {
    value: "Bangladesh Standard Time",
    abbr: "BST",
    offset: 6,
    isdst: false,
    text: "(UTC+06:00) Dhaka",
    utc: ["Asia/Dhaka", "Asia/Thimphu"],
  },
  {
    value: "Myanmar Standard Time",
    abbr: "MST",
    offset: 6.5,
    isdst: false,
    text: "(UTC+06:30) Yangon (Rangoon)",
    utc: ["Asia/Rangoon", "Indian/Cocos"],
  },
  {
    value: "SE Asia Standard Time",
    abbr: "SAST",
    offset: 7,
    isdst: false,
    text: "(UTC+07:00) Bangkok, Hanoi, Jakarta",
    utc: [
      "Antarctica/Davis",
      "Asia/Bangkok",
      "Asia/Hovd",
      "Asia/Jakarta",
      "Asia/Phnom_Penh",
      "Asia/Pontianak",
      "Asia/Saigon",
      "Asia/Vientiane",
      "Etc/GMT-7",
      "Indian/Christmas",
    ],
  },
  {
    value: "N. Central Asia Standard Time",
    abbr: "NCAST",
    offset: 7,
    isdst: false,
    text: "(UTC+07:00) Novosibirsk",
    utc: ["Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Omsk"],
  },
  {
    value: "China Standard Time",
    abbr: "CST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
    utc: ["Asia/Hong_Kong", "Asia/Macau", "Asia/Shanghai"],
  },
  {
    value: "North Asia Standard Time",
    abbr: "NAST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Krasnoyarsk",
    utc: ["Asia/Krasnoyarsk"],
  },
  {
    value: "Singapore Standard Time",
    abbr: "MPST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Kuala Lumpur, Singapore",
    utc: [
      "Asia/Brunei",
      "Asia/Kuala_Lumpur",
      "Asia/Kuching",
      "Asia/Makassar",
      "Asia/Manila",
      "Asia/Singapore",
      "Etc/GMT-8",
    ],
  },
  {
    value: "W. Australia Standard Time",
    abbr: "WAST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Perth",
    utc: ["Antarctica/Casey", "Australia/Perth"],
  },
  {
    value: "Taipei Standard Time",
    abbr: "TST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Taipei",
    utc: ["Asia/Taipei"],
  },
  {
    value: "Ulaanbaatar Standard Time",
    abbr: "UST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Ulaanbaatar",
    utc: ["Asia/Choibalsan", "Asia/Ulaanbaatar"],
  },
  {
    value: "North Asia East Standard Time",
    abbr: "NAEST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Irkutsk",
    utc: ["Asia/Irkutsk"],
  },
  {
    value: "Japan Standard Time",
    abbr: "JST",
    offset: 9,
    isdst: false,
    text: "(UTC+09:00) Osaka, Sapporo, Tokyo",
    utc: [
      "Asia/Dili",
      "Asia/Jayapura",
      "Asia/Tokyo",
      "Etc/GMT-9",
      "Pacific/Palau",
    ],
  },
  {
    value: "Korea Standard Time",
    abbr: "KST",
    offset: 9,
    isdst: false,
    text: "(UTC+09:00) Seoul",
    utc: ["Asia/Pyongyang", "Asia/Seoul"],
  },
  {
    value: "Cen. Australia Standard Time",
    abbr: "CAST",
    offset: 9.5,
    isdst: false,
    text: "(UTC+09:30) Adelaide",
    utc: ["Australia/Adelaide", "Australia/Broken_Hill"],
  },
  {
    value: "AUS Central Standard Time",
    abbr: "ACST",
    offset: 9.5,
    isdst: false,
    text: "(UTC+09:30) Darwin",
    utc: ["Australia/Darwin"],
  },
  {
    value: "E. Australia Standard Time",
    abbr: "EAST",
    offset: 10,
    isdst: false,
    text: "(UTC+10:00) Brisbane",
    utc: ["Australia/Brisbane", "Australia/Lindeman"],
  },
  {
    value: "AUS Eastern Standard Time",
    abbr: "AEST",
    offset: 10,
    isdst: false,
    text: "(UTC+10:00) Canberra, Melbourne, Sydney",
    utc: ["Australia/Melbourne", "Australia/Sydney"],
  },
  {
    value: "West Pacific Standard Time",
    abbr: "WPST",
    offset: 10,
    isdst: false,
    text: "(UTC+10:00) Guam, Port Moresby",
    utc: [
      "Antarctica/DumontDUrville",
      "Etc/GMT-10",
      "Pacific/Guam",
      "Pacific/Port_Moresby",
      "Pacific/Saipan",
      "Pacific/Truk",
    ],
  },
  {
    value: "Tasmania Standard Time",
    abbr: "TST",
    offset: 10,
    isdst: false,
    text: "(UTC+10:00) Hobart",
    utc: ["Australia/Currie", "Australia/Hobart"],
  },
  {
    value: "Yakutsk Standard Time",
    abbr: "YST",
    offset: 9,
    isdst: false,
    text: "(UTC+09:00) Yakutsk",
    utc: ["Asia/Chita", "Asia/Khandyga", "Asia/Yakutsk"],
  },
  {
    value: "Central Pacific Standard Time",
    abbr: "CPST",
    offset: 11,
    isdst: false,
    text: "(UTC+11:00) Solomon Is., New Caledonia",
    utc: [
      "Antarctica/Macquarie",
      "Etc/GMT-11",
      "Pacific/Efate",
      "Pacific/Guadalcanal",
      "Pacific/Kosrae",
      "Pacific/Noumea",
      "Pacific/Ponape",
    ],
  },
  {
    value: "Vladivostok Standard Time",
    abbr: "VST",
    offset: 11,
    isdst: false,
    text: "(UTC+11:00) Vladivostok",
    utc: ["Asia/Sakhalin", "Asia/Ust-Nera", "Asia/Vladivostok"],
  },
  {
    value: "New Zealand Standard Time",
    abbr: "NZST",
    offset: 12,
    isdst: false,
    text: "(UTC+12:00) Auckland, Wellington",
    utc: ["Antarctica/McMurdo", "Pacific/Auckland"],
  },
  {
    value: "UTC+12",
    abbr: "U",
    offset: 12,
    isdst: false,
    text: "(UTC+12:00) Coordinated Universal Time+12",
    utc: [
      "Etc/GMT-12",
      "Pacific/Funafuti",
      "Pacific/Kwajalein",
      "Pacific/Majuro",
      "Pacific/Nauru",
      "Pacific/Tarawa",
      "Pacific/Wake",
      "Pacific/Wallis",
    ],
  },
  {
    value: "Fiji Standard Time",
    abbr: "FST",
    offset: 12,
    isdst: false,
    text: "(UTC+12:00) Fiji",
    utc: ["Pacific/Fiji"],
  },
  {
    value: "Magadan Standard Time",
    abbr: "MST",
    offset: 12,
    isdst: false,
    text: "(UTC+12:00) Magadan",
    utc: [
      "Asia/Anadyr",
      "Asia/Kamchatka",
      "Asia/Magadan",
      "Asia/Srednekolymsk",
    ],
  },
  {
    value: "Kamchatka Standard Time",
    abbr: "KDT",
    offset: 13,
    isdst: true,
    text: "(UTC+12:00) Petropavlovsk-Kamchatsky - Old",
    utc: ["Asia/Kamchatka"],
  },
  {
    value: "Tonga Standard Time",
    abbr: "TST",
    offset: 13,
    isdst: false,
    text: "(UTC+13:00) Nuku'alofa",
    utc: [
      "Etc/GMT-13",
      "Pacific/Enderbury",
      "Pacific/Fakaofo",
      "Pacific/Tongatapu",
    ],
  },
  {
    value: "Samoa Standard Time",
    abbr: "SST",
    offset: 13,
    isdst: false,
    text: "(UTC+13:00) Samoa",
    utc: ["Pacific/Apia"],
  },
]
export const scheduleArray = [
  {
    id: "wk01",
    week: "Week 1",
    schedule: [
      {
        id: "100",
        name: "sunday",
        option: [
          {
            weekId: "wk01",
            week: "week 1",
            id: "101",
            name: "sunday",
            time: "9",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "102",
            name: "sunday",
            time: "10",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "103",
            name: "sunday",
            time: "11",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "104",
            name: "sunday",
            time: "12",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "105",
            name: "sunday",
            time: "1",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "106",
            name: "sunday",
            time: "2",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "107",
            name: "sunday",
            time: "3",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "108",
            name: "sunday",
            time: "4",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "109",
            name: "sunday",
            time: "5",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1010",
            name: "sunday",
            time: "6",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1011",
            name: "sunday",
            time: "7",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1012",
            name: "sunday",
            time: "8",
          },
        ],
      },
      {
        id: "120",
        name: "monday",
        option: [
          {
            weekId: "wk01",
            week: "week 1",
            id: "121",
            name: "monday",
            time: "9",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "122",
            name: "monday",
            time: "10",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "123",
            name: "monday",
            time: "11",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "124",
            name: "monday",
            time: "12",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "125",
            name: "monday",
            time: "1",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "126",
            name: "monday",
            time: "2",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "127",
            name: "monday",
            time: "3",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "128",
            name: "monday",
            time: "4",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "129",
            name: "monday",
            time: "5",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1210",
            name: "monday",
            time: "6",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1211",
            name: "monday",
            time: "7",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1212",
            name: "monday",
            time: "8",
          },
        ],
      },
      {
        id: "130",
        name: "tuesday",
        option: [
          {
            weekId: "wk01",
            week: "week 1",
            id: "131",
            name: "tuesday",
            time: "9",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "132",
            name: "tuesday",
            time: "10",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "133",
            name: "tuesday",
            time: "11",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "134",
            name: "tuesday",
            time: "12",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "135",
            name: "tuesday",
            time: "1",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "136",
            name: "tuesday",
            time: "2",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "137",
            name: "tuesday",
            time: "3",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "138",
            name: "tuesday",
            time: "4",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "139",
            name: "tuesday",
            time: "5",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1310",
            name: "tuesday",
            time: "6",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1311",
            name: "tuesday",
            time: "7",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1312",
            name: "tuesday",
            time: "8",
          },
        ],
      },
      {
        id: "140",
        name: "wednesday",
        option: [
          {
            weekId: "wk01",
            week: "week 1",
            id: "141",
            name: "wednesday",
            time: "9",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "142",
            name: "wednesday",
            time: "10",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "143",
            name: "wednesday",
            time: "11",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "144",
            name: "wednesday",
            time: "12",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "145",
            name: "wednesday",
            time: "1",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "146",
            name: "wednesday",
            time: "2",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "147",
            name: "wednesday",
            time: "3",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "148",
            name: "wednesday",
            time: "4",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "149",
            name: "wednesday",
            time: "5",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1410",
            name: "wednesday",
            time: "6",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1411",
            name: "wednesday",
            time: "7",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1412",
            name: "wednesday",
            time: "8",
          },
        ],
      },
      {
        id: "150",
        name: "thursday",
        option: [
          {
            weekId: "wk01",
            week: "week 1",
            id: "151",
            name: "thursday",
            time: "9",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "152",
            name: "thursday",
            time: "10",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "153",
            name: "thursday",
            time: "11",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "154",
            name: "thursday",
            time: "12",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "155",
            name: "thursday",
            time: "1",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "156",
            name: "thursday",
            time: "2",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "157",
            name: "thursday",
            time: "3",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "158",
            name: "thursday",
            time: "4",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "159",
            name: "thursday",
            time: "5",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1510",
            name: "thursday",
            time: "6",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1511",
            name: "thursday",
            time: "7",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1512",
            name: "thursday",
            time: "8",
          },
        ],
      },
      {
        id: "160",
        name: "friday",
        option: [
          {
            weekId: "wk01",
            week: "week 1",
            id: "161",
            name: "friday",
            time: "9",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "162",
            name: "friday",
            time: "10",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "163",
            name: "friday",
            time: "11",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "164",
            name: "friday",
            time: "12",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "165",
            name: "friday",
            time: "1",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "166",
            name: "friday",
            time: "2",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "167",
            name: "friday",
            time: "3",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "168",
            name: "friday",
            time: "4",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "169",
            name: "friday",
            time: "5",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1610",
            name: "friday",
            time: "6",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1611",
            name: "friday",
            time: "7",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1612",
            name: "friday",
            time: "8",
          },
        ],
      },
      {
        id: "170",
        name: "saturday",
        option: [
          {
            weekId: "wk01",
            week: "week 1",
            id: "171",
            name: "saturday",
            time: "9",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "172",
            name: "saturday",
            time: "10",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "173",
            name: "saturday",
            time: "11",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "174",
            name: "saturday",
            time: "12",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "175",
            name: "saturday",
            time: "1",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "176",
            name: "saturday",
            time: "2",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "177",
            name: "saturday",
            time: "3",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "178",
            name: "saturday",
            time: "4",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "179",
            name: "saturday",
            time: "5",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1710",
            name: "saturday",
            time: "6",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1711",
            name: "saturday",
            time: "7",
          },
          {
            weekId: "wk01",
            week: "week 1",
            id: "1712",
            name: "saturday",
            time: "8",
          },
        ],
      },
    ],
  },
  {
    id: "wk02",
    week: "Week 2",
    schedule: [
      {
        id: "200",
        name: "sunday",
        option: [
          {
            weekId: "wk02",
            week: "week 2",
            id: "201",
            name: "sunday",
            time: "9",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "202",
            name: "sunday",
            time: "10",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "203",
            name: "sunday",
            time: "11",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "204",
            name: "sunday",
            time: "12",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "205",
            name: "sunday",
            time: "1",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "206",
            name: "sunday",
            time: "2",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "207",
            name: "sunday",
            time: "3",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "208",
            name: "sunday",
            time: "4",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "209",
            name: "sunday",
            time: "5",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2010",
            name: "sunday",
            time: "6",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2011",
            name: "sunday",
            time: "7",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2012",
            name: "sunday",
            time: "8",
          },
        ],
      },
      {
        id: "2100",
        name: "monday",
        option: [
          {
            weekId: "wk02",
            week: "week 2",
            id: "2101",
            name: "monday",
            time: "9",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2102",
            name: "monday",
            time: "10",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2103",
            name: "monday",
            time: "11",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2104",
            name: "monday",
            time: "12",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2105",
            name: "monday",
            time: "1",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2106",
            name: "monday",
            time: "2",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2107",
            name: "monday",
            time: "3",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2108",
            name: "monday",
            time: "4",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2109",
            name: "monday",
            time: "5",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "21010",
            name: "monday",
            time: "6",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "21011",
            name: "monday",
            time: "7",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "21012",
            name: "monday",
            time: "8",
          },
        ],
      },
      {
        id: "2300",
        name: "tuesday",
        option: [
          {
            weekId: "wk02",
            week: "week 2",
            id: "2301",
            name: "tuesday",
            time: "9",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2302",
            name: "tuesday",
            time: "10",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2303",
            name: "tuesday",
            time: "11",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2304",
            name: "tuesday",
            time: "12",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2305",
            name: "tuesday",
            time: "1",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2306",
            name: "tuesday",
            time: "2",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2307",
            name: "tuesday",
            time: "3",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2308",
            name: "tuesday",
            time: "4",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2309",
            name: "tuesday",
            time: "5",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "23010",
            name: "tuesday",
            time: "6",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "23011",
            name: "tuesday",
            time: "7",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "23012",
            name: "tuesday",
            time: "8",
          },
        ],
      },
      {
        id: "2040",
        name: "wednesday",
        option: [
          {
            weekId: "wk02",
            week: "week 2",
            id: "2041",
            name: "wednesday",
            time: "9",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2042",
            name: "wednesday",
            time: "10",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2043",
            name: "wednesday",
            time: "11",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2044",
            name: "wednesday",
            time: "12",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2045",
            name: "wednesday",
            time: "1",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2046",
            name: "wednesday",
            time: "2",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2047",
            name: "wednesday",
            time: "3",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2048",
            name: "wednesday",
            time: "4",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2049",
            name: "wednesday",
            time: "5",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20410",
            name: "wednesday",
            time: "6",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20411",
            name: "wednesday",
            time: "7",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20412",
            name: "wednesday",
            time: "8",
          },
        ],
      },
      {
        id: "2050",
        name: "thursday",
        option: [
          {
            weekId: "wk02",
            week: "week 2",
            id: "2051",
            name: "thursday",
            time: "9",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2052",
            name: "thursday",
            time: "10",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2053",
            name: "thursday",
            time: "11",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2054",
            name: "thursday",
            time: "12",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2055",
            name: "thursday",
            time: "1",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2056",
            name: "thursday",
            time: "2",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2057",
            name: "thursday",
            time: "3",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2058",
            name: "thursday",
            time: "4",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2059",
            name: "thursday",
            time: "5",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20510",
            name: "thursday",
            time: "6",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20511",
            name: "thursday",
            time: "7",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20512",
            name: "thursday",
            time: "8",
          },
        ],
      },
      {
        id: "2060",
        name: "friday",
        option: [
          {
            weekId: "wk02",
            week: "week 2",
            id: "2061",
            name: "friday",
            time: "9",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2062",
            name: "friday",
            time: "10",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2063",
            name: "friday",
            time: "11",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2064",
            name: "friday",
            time: "12",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2065",
            name: "friday",
            time: "1",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2066",
            name: "friday",
            time: "2",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2067",
            name: "friday",
            time: "3",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2068",
            name: "friday",
            time: "4",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2069",
            name: "friday",
            time: "5",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20610",
            name: "friday",
            time: "6",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20611",
            name: "friday",
            time: "7",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20612",
            name: "friday",
            time: "8",
          },
        ],
      },
      {
        id: "2070",
        name: "saturday",
        option: [
          {
            weekId: "wk02",
            week: "week 2",
            id: "2071",
            name: "saturday",
            time: "9",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2072",
            name: "saturday",
            time: "10",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2073",
            name: "saturday",
            time: "11",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2074",
            name: "saturday",
            time: "12",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2075",
            name: "saturday",
            time: "1",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2076",
            name: "saturday",
            time: "2",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2077",
            name: "saturday",
            time: "3",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2078",
            name: "saturday",
            time: "4",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "2079",
            name: "saturday",
            time: "5",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20710",
            name: "saturday",
            time: "6",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20711",
            name: "saturday",
            time: "7",
          },
          {
            weekId: "wk02",
            week: "week 2",
            id: "20712",
            name: "saturday",
            time: "8",
          },
        ],
      },
    ],
  },
  {
    id: "wk03",
    week: "Week 3",
    schedule: [
      {
        id: "300",
        name: "sunday",
        option: [
          {
            weekId: "wk03",
            week: "week 3",
            id: "301",
            name: "sunday",
            time: "9",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "302",
            name: "sunday",
            time: "10",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "303",
            name: "sunday",
            time: "11",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "304",
            name: "sunday",
            time: "12",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "305",
            name: "sunday",
            time: "1",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "306",
            name: "sunday",
            time: "2",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "307",
            name: "sunday",
            time: "3",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "308",
            name: "sunday",
            time: "4",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "309",
            name: "sunday",
            time: "5",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3010",
            name: "sunday",
            time: "6",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3011",
            name: "sunday",
            time: "7",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3012",
            name: "sunday",
            time: "8",
          },
        ],
      },
      {
        id: "310",
        name: "monday",
        option: [
          {
            weekId: "wk03",
            week: "week 3",
            id: "3101",
            name: "monday",
            time: "9",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3102",
            name: "monday",
            time: "10",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3103",
            name: "monday",
            time: "11",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3104",
            name: "monday",
            time: "12",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3105",
            name: "monday",
            time: "1",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3106",
            name: "monday",
            time: "2",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3107",
            name: "monday",
            time: "3",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3108",
            name: "monday",
            time: "4",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3109",
            name: "monday",
            time: "5",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3110",
            name: "monday",
            time: "6",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3111",
            name: "monday",
            time: "7",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3112",
            name: "monday",
            time: "8",
          },
        ],
      },
      {
        id: "320",
        name: "tuesday",
        option: [
          {
            weekId: "wk03",
            week: "week 3",
            id: "3201",
            name: "tuesday",
            time: "9",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3202",
            name: "tuesday",
            time: "10",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3203",
            name: "tuesday",
            time: "11",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3204",
            name: "tuesday",
            time: "12",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3205",
            name: "tuesday",
            time: "1",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3206",
            name: "tuesday",
            time: "2",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3207",
            name: "tuesday",
            time: "3",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3208",
            name: "tuesday",
            time: "4",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3209",
            name: "tuesday",
            time: "5",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "32010",
            name: "tuesday",
            time: "6",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "32011",
            name: "tuesday",
            time: "7",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "32012",
            name: "tuesday",
            time: "8",
          },
        ],
      },
      {
        id: "330",
        name: "wednesday",
        option: [
          {
            weekId: "wk03",
            week: "week 3",
            id: "3301",
            name: "wednesday",
            time: "9",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3302",
            name: "wednesday",
            time: "10",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3303",
            name: "wednesday",
            time: "11",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3304",
            name: "wednesday",
            time: "12",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3305",
            name: "wednesday",
            time: "1",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3306",
            name: "wednesday",
            time: "2",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3307",
            name: "wednesday",
            time: "3",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3308",
            name: "wednesday",
            time: "4",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3309",
            name: "wednesday",
            time: "5",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "33010",
            name: "wednesday",
            time: "6",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "33011",
            name: "wednesday",
            time: "7",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "33012",
            name: "wednesday",
            time: "8",
          },
        ],
      },
      {
        id: "340",
        name: "thursday",
        option: [
          {
            weekId: "wk03",
            week: "week 3",
            id: "3401",
            name: "thursday",
            time: "9",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3402",
            name: "thursday",
            time: "10",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3403",
            name: "thursday",
            time: "11",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3404",
            name: "thursday",
            time: "12",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3405",
            name: "thursday",
            time: "1",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3406",
            name: "thursday",
            time: "2",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3407",
            name: "thursday",
            time: "3",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3408",
            name: "thursday",
            time: "4",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3409",
            name: "thursday",
            time: "5",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "34010",
            name: "thursday",
            time: "6",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "34011",
            name: "thursday",
            time: "7",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "34012",
            name: "thursday",
            time: "8",
          },
        ],
      },
      {
        id: "350",
        name: "friday",
        option: [
          {
            weekId: "wk03",
            week: "week 3",
            id: "3501",
            name: "friday",
            time: "9",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3502",
            name: "friday",
            time: "10",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3503",
            name: "friday",
            time: "11",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3504",
            name: "friday",
            time: "12",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3505",
            name: "friday",
            time: "1",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3506",
            name: "friday",
            time: "2",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3507",
            name: "friday",
            time: "3",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3508",
            name: "friday",
            time: "4",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3509",
            name: "friday",
            time: "5",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "35010",
            name: "friday",
            time: "6",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "35011",
            name: "friday",
            time: "7",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "35012",
            name: "friday",
            time: "8",
          },
        ],
      },
      {
        id: "360",
        name: "saturday",
        option: [
          {
            weekId: "wk03",
            week: "week 3",
            id: "3601",
            name: "saturday",
            time: "9",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3602",
            name: "saturday",
            time: "10",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3603",
            name: "saturday",
            time: "11",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3604",
            name: "saturday",
            time: "12",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3605",
            name: "saturday",
            time: "1",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3606",
            name: "saturday",
            time: "2",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3607",
            name: "saturday",
            time: "3",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3608",
            name: "saturday",
            time: "4",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "3609",
            name: "saturday",
            time: "5",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "36010",
            name: "saturday",
            time: "6",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "36011",
            name: "saturday",
            time: "7",
          },
          {
            weekId: "wk03",
            week: "week 3",
            id: "36012",
            name: "saturday",
            time: "8",
          },
        ],
      },
    ],
  },
  {
    id: "wk04",
    week: "Week 4",
    schedule: [
      {
        id: "400",
        name: "sunday",
        option: [
          {
            weekId: "wk04",
            week: "week 4",
            id: "401",
            name: "sunday",
            time: "9",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "402",
            name: "sunday",
            time: "10",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "403",
            name: "sunday",
            time: "11",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "404",
            name: "sunday",
            time: "12",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "405",
            name: "sunday",
            time: "1",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "406",
            name: "sunday",
            time: "2",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "407",
            name: "sunday",
            time: "3",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "408",
            name: "sunday",
            time: "4",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "409",
            name: "sunday",
            time: "5",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4010",
            name: "sunday",
            time: "6",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4011",
            name: "sunday",
            time: "7",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4012",
            name: "sunday",
            time: "8",
          },
        ],
      },
      {
        id: "400",
        name: "monday",
        option: [
          {
            weekId: "wk04",
            week: "week 4",
            id: "401",
            name: "monday",
            time: "9",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "402",
            name: "monday",
            time: "10",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "403",
            name: "monday",
            time: "11",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "404",
            name: "monday",
            time: "12",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "405",
            name: "monday",
            time: "1",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "406",
            name: "monday",
            time: "2",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "407",
            name: "monday",
            time: "3",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "408",
            name: "monday",
            time: "4",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "409",
            name: "monday",
            time: "5",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4010",
            name: "monday",
            time: "6",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4011",
            name: "monday",
            time: "7",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4012",
            name: "monday",
            time: "8",
          },
        ],
      },
      {
        id: "410",
        name: "tuesday",
        option: [
          {
            weekId: "wk04",
            week: "week 4",
            id: "4101",
            name: "tuesday",
            time: "9",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4102",
            name: "tuesday",
            time: "10",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4103",
            name: "tuesday",
            time: "11",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4104",
            name: "tuesday",
            time: "12",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4105",
            name: "tuesday",
            time: "1",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4106",
            name: "tuesday",
            time: "2",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "316",
            name: "tuesday",
            time: "3",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4107",
            name: "tuesday",
            time: "4",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4108",
            name: "tuesday",
            time: "5",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4109",
            name: "tuesday",
            time: "6",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "41010",
            name: "tuesday",
            time: "7",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "41011",
            name: "tuesday",
            time: "8",
          },
        ],
      },
      {
        id: "420",
        name: "wednesday",
        option: [
          {
            weekId: "wk04",
            week: "week 4",
            id: "4201",
            name: "wednesday",
            time: "9",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4202",
            name: "wednesday",
            time: "10",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4203",
            name: "wednesday",
            time: "11",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4204",
            name: "wednesday",
            time: "12",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4205",
            name: "wednesday",
            time: "1",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4206",
            name: "wednesday",
            time: "2",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4207",
            name: "wednesday",
            time: "3",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4208",
            name: "wednesday",
            time: "4",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4209",
            name: "wednesday",
            time: "5",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "42010",
            name: "wednesday",
            time: "6",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "42011",
            name: "wednesday",
            time: "7",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "42012",
            name: "wednesday",
            time: "8",
          },
        ],
      },
      {
        id: "430",
        name: "thursday",
        option: [
          {
            weekId: "wk04",
            week: "week 4",
            id: "4301",
            name: "thursday",
            time: "9",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4302",
            name: "thursday",
            time: "10",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4304",
            name: "thursday",
            time: "11",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4305",
            name: "thursday",
            time: "12",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4306",
            name: "thursday",
            time: "1",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4307",
            name: "thursday",
            time: "2",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4308",
            name: "thursday",
            time: "3",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4309",
            name: "thursday",
            time: "4",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "43010",
            name: "thursday",
            time: "5",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "43011",
            name: "thursday",
            time: "6",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "43012",
            name: "thursday",
            time: "7",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "43013",
            name: "thursday",
            time: "8",
          },
        ],
      },
      {
        id: "440",
        name: "friday",
        option: [
          {
            weekId: "wk04",
            week: "week 4",
            id: "4401",
            name: "friday",
            time: "9",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4402",
            name: "friday",
            time: "10",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4403",
            name: "friday",
            time: "11",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4404",
            name: "friday",
            time: "12",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4405",
            name: "friday",
            time: "1",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4406",
            name: "friday",
            time: "2",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4407",
            name: "friday",
            time: "3",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4408",
            name: "friday",
            time: "4",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4409",
            name: "friday",
            time: "5",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "44010",
            name: "friday",
            time: "6",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "44011",
            name: "friday",
            time: "7",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "44012",
            name: "friday",
            time: "8",
          },
        ],
      },
      {
        id: "450",
        name: "saturday",
        option: [
          {
            weekId: "wk04",
            week: "week 4",
            id: "4501",
            name: "saturday",
            time: "9",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4502",
            name: "saturday",
            time: "10",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4503",
            name: "saturday",
            time: "11",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4504",
            name: "saturday",
            time: "12",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4504",
            name: "saturday",
            time: "1",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4505",
            name: "saturday",
            time: "2",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4506",
            name: "saturday",
            time: "3",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4507",
            name: "saturday",
            time: "4",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4508",
            name: "saturday",
            time: "5",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "4509",
            name: "saturday",
            time: "6",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "45010",
            name: "saturday",
            time: "7",
          },
          {
            weekId: "wk04",
            week: "week 4",
            id: "45011",
            name: "saturday",
            time: "8",
          },
        ],
      },
    ],
  },
]
